mode: auto
branchName: ${{ github.event.issue.user.login }}/${{ github.event.issue.number }}/${{ github.event.issue.title }}
defaultBranch: main
openPR: true
copyIssueDescriptionToPR: true
copyIssueLabelsToPR: true