# https://github.com/robvanderleek/create-issue-branch#option-2-configure-github-action
mode: auto
silent: false
branchName: '${github.event.issue.user.login}/${github.event.issue.number}-${issue.title}'
autoCloseIssue: true
gitSafeReplacementChar: "-"
openPR: true
copyIssueDescriptionToPR: true
copyIssueLabelsToPR: true