name: Create Issue Branch and Open PR
on:
  # The issues event below is only needed for the default (auto) mode,
  # you can remove it otherwise
  issues:
    types: [ assigned ]
  # The issue_comment event below is only needed for the ChatOps mode,
  # you can remove it otherwise


jobs:
  create_issue_branch_job:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue Branch
        id: Create_Issue_Branch
        uses: robvanderleek/create-issue-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Echo branch name'
        run: echo ${{ steps.Create_Issue_Branch.outputs.branchName }}

      - name: Find PR number
        id: find_pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # get the pr number by querying the github api
          PR_URL=$(gh api repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/timeline | jq '.[] | .source.issue.pull_request.url | select(. != null)')
          PR_NUMBER=$(echo $PR_URL | cut -d'/' -f8 | cut -d'"' -f1)
          echo "PR=$PR_NUMBER"
          echo "PR=$PR_NUMBER" >> $GITHUB_OUTPUT

      - name: Comment on PR
        uses: actions-cool/issues-helper@v2
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ steps.find_pr.outputs.PR }}
          body: |
            Nice to see you again! :wave:

            Let's get going and start deploying code. All you need to do is add the **deploy environment** label to this pull request and I'll take care of the rest. Use the side bar to the right to add the label. :point_right:

      - name: Comment on PR
        uses: actions-cool/issues-helper@v2
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Alright, I've created a new branch and pull request for you. You will interact with the GitHub Actions bot :robot: over on the pull request.

            You can access the pull request here: **https://github.com/${{ github.repository }}/pull/${{ steps.find_pr.outputs.PR }}**

            See you there! :wave:

