name: Create Issue Branch and Open PR
on:
  # The issues event below is only needed for the default (auto) mode,
  # you can remove it otherwise
  issues:
    types: [ assigned ]
  # The issue_comment event below is only needed for the ChatOps mode,
  # you can remove it otherwise


jobs:
  create_issue_branch_job:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue Branch
        id: Create_Issue_Branch
        uses: robvanderleek/create-issue-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Echo branch name'
        run: echo ${{ steps.Create_Issue_Branch.outputs.branchName }}

      - name: Find PR number
        id: find_pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # get the pr number by querying the github api
          PR_URL=$(gh api repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/timeline | jq '.[] | .source.issue.pull_request.url | select(. != null)')
          PR_NUMBER=$(echo $PR_URL | cut -d'/' -f8 | cut -d'"' -f1)
          echo "PR: $PR_NUMBER"

