name: Software Factory

on:
  pull_request:
    types: [ opened, labeled ]
  push:
    branches-ignore:
    - 'main'

jobs:
  post_comment:
    runs-on: ubuntu-latest
    name: Build Output
    steps:
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### :factory: Software Factory Build Output ###
            ---
            I'll update this comment to show the progress of your deployment (using beautiful GitHub **Markdown** :sparkles: )

            | Status | Task |
            | --- | --- |
            | ![](https://img.shields.io/badge/InProgress-blue?style=plastic) |  Deploy Google Cloud Run using Terraform |
            | ![](https://img.shields.io/badge/Waiting-lightgrey?style=plastic) | Build Docker image and deploy to Cloud Run instance |

            Application URL: *not yet ready*
          reactions: 'rocket'

  deploy-infrastructure:
    uses: ./.github/workflows/template-terraform-deploy.yml
    secrets: inherit

  deploy-app:
    uses: ./.github/workflows/template-docker-deploy.yml
    secrets: inherit
    needs: deploy-infrastructure

# ### Software Factory Build Output ###
# ---
# I'll update this comment to show the progress of your deployment (using beautiful GitHub **Markdown** ✨ )

# | Status | Task |
# | --- | --- |
# | ![](https://img.shields.io/badge/InProgress-blue?style=plastic) |  Deploy Google Cloud Run using Terraform |
# | ![](https://img.shields.io/badge/Waiting-lightgrey?style=plastic) | Build Docker image and deploy to Cloud Run instance |

# Application URL: *not yet ready*

# ![](https://img.shields.io/badge/InProgress-blue?style=plastic)
# ![](https://img.shields.io/badge/Waiting-lightgrey?style=plastic)
# ![](https://img.shields.io/badge/Finished-brightgreen?style=plastic)
