name: Docker Image CI

on:
  #push:
  #  branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.GCP_SA_CREDENTIAL }}
        token_format: access_token

    #This example runs "docker login" directly to Artifact Registry.
    - uses: docker/login-action@v1
      with:
        registry: us-east1-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}

    - name: Build the Docker image
      run: |
        ENV_ID=$(echo $GITHUB_REF_NAME | base64 | tr -d '=/!' | tr '[:upper:]' '[:lower:]'| tail -c 9)
        docker build . --file Dockerfile --tag us-east1-docker.pkg.dev/acampbell-sc-lab/artifacts-dsdemo-$ENV_ID/timecard-memer:${{ github.sha }}
      working-directory: containers/timecard-memer

    - name: Push the Docker image
      run: |
        ENV_ID=$(echo $GITHUB_REF_NAME | base64 | tr -d '=/!' | tr '[:upper:]' '[:lower:]'| tail -c 9)
        docker push us-east1-docker.pkg.dev/acampbell-sc-lab/artifacts-dsdemo-$ENV_ID/timecard-memer:${{ github.sha }}
      working-directory: containers/timecard-memer
