name: Create Comment

on:
  issues:
    types: [opened]

jobs:
  create-comment:
    runs-on: ubuntu-latest
    #if: github.event.label.name == 'gcp'
    steps:
      - name: Create comment
        uses: actions-cool/issues-helper@v2
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            :wave: Hey there! I'm the GitHub Actions bot, and I'll be helping you get a new environment up and running!

            Start the process by assigning this issue to yourself. You can use the `Assignees` menu on the right side of the issue and click **assign yourself**.

            I'll take it from there and do the following for you:

            1. Create a new branch for your environment named `dsdemo-${{ github.event.issue.number }}`
            2. Open a new Pull Request for your environment
            3. Add a welcome comment to your Pull Request with instructions on next steps
            4. Provide a link to your Pull Request in this issue and we will continue the process there
          contents: 'heart'

