name: Create Comment

on:
  issues:
    types: [opened]

jobs:
  create-comment:
    runs-on: ubuntu-latest
    #if: github.event.label.name == 'gcp'
    steps:
      - name: Create comment
        uses: actions-cool/issues-helper@v2
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Looks like you want to provision a new environment, let's get started! :tada:

            We'll take a couple of steps to get you up and running.'
            1. Create a new branch for your environment named `${{ github.event.issue.user.login }}-dsdemo-${{ github.event.issue.number }}`
            2. Create a new Pull Request for your environment

            The rest of the automation will interact with the Pull Requst. Once it is
            created we'll share the link with you in another comment.
          # body: |
          #   Hello @${{ github.event.issue.user.login }}.
          #   Thanks for opening this issue!
          #   This was generated from GitHub Actions.
          contents: 'heart'

