name: Docker Deploy

on:
  #push:
  #  branches: [ "main" ]
  workflow_dispatch:
  workflow_call:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"

    - name: Get branch name
      id: get_branch_name
      run: |
        # if the event is a pull request, use the head ref
        if [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
          BRANCH=$GITHUB_HEAD_REF
        else
          # otherwise, use the ref name
          BRANCH=$GITHUB_REF_NAME
        fi
        echo "head_ref: $GITHUB_HEAD_REF"
        echo "ref_name: $GITHUB_REF_NAME"
        echo "branch: $BRANCH"
        echo "BRANCH=$BRANCH" >> $GITHUB_OUTPUT

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.GCP_SA_CREDENTIAL }}
        token_format: access_token

    #This example runs "docker login" directly to Artifact Registry.
    - uses: docker/login-action@v1
      with:
        registry: us-east1-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag us-east1-docker.pkg.dev/acampbell-sc-lab/artifacts-${{ steps.get_branch_name.outputs.BRANCH }}/app:${{ github.sha }}
      working-directory: containers/app

    - name: Push the Docker image
      run: |
        docker push us-east1-docker.pkg.dev/acampbell-sc-lab/artifacts-${{ steps.get_branch_name.outputs.BRANCH }}/app:${{ github.sha }}
      working-directory: containers/app

    - name: Deploy Docker image to Cloud Run
      run: |
        gcloud run deploy cloudrun-${{ steps.get_branch_name.outputs.BRANCH }} --image us-east1-docker.pkg.dev/acampbell-sc-lab/artifacts-${{ steps.get_branch_name.outputs.BRANCH }}/app:${{ github.sha }} --platform managed --region us-east1 --allow-unauthenticated --port 80
      working-directory: containers/app

    - name: Get the Cloud Run URL
      id: get_url
      run: |
        URL=$(gcloud run services describe cloudrun-${{ steps.get_branch_name.outputs.BRANCH }} --region us-east1 --format 'value(status.url)')
        echo $URL
        echo "CLOUDRUN_URL=$URL" >> $GITHUB_OUTPUT

    - name: Print the Cloud Run URL
      run: |
        echo "Obtained Cloud Run URL: ${{ steps.get_url.outputs.CLOUDRUN_URL }}"

    - name: Post comment to PR
      if: github.event_name == 'pull_request'
      uses: actions-cool/issues-helper@v2
      with:
        actions: 'create-comment'
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          :rocket: Application has been deployed to ${{ steps.get_url.outputs.CLOUDRUN_URL }}.

    - name: Find Comment
      if: github.event_name == 'pull_request' && github.event.action == 'labeled' && github.event.label.name == 'deploy environment'
      uses: peter-evans/find-comment@v2
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: Software Factory Build Output

    - name: Create or update comment
      if: github.event_name == 'pull_request' && github.event.action == 'labeled' && github.event.label.name == 'deploy environment'
      uses: peter-evans/create-or-update-comment@v2
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          ### :factory: Software Factory Build Output ###
          ---
          I'll update this comment to show the progress of your deployment (using beautiful GitHub **Markdown** :sparkles: )

          | Status | Task |
          | --- | --- |
          | ![](https://img.shields.io/badge/Complete-brightgreen?style=plastic) |  Deploy Google Cloud Run using Terraform |
          | ![](https://img.shields.io/badge/Complete-brightgreen?style=plastic) | Build Docker image and deploy to Cloud Run instance |

          Application URL: **${{ steps.get_url.outputs.CLOUDRUN_URL }}**
        reactions: 'rocket'
        edit-mode: replace

