name: Terraform Deploy

on:
  workflow_dispatch:
  workflow_call:


jobs:
  test:
    defaults:
      run:
        working-directory: terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GCP_SA_CREDENTIAL }}

      # Install gcloud, `setup-gcloud` automatically picks up authentication from `auth`.
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - id: 'gcloud'
        name: 'gcloud'
        run: |
          gcloud config list

      - uses: hashicorp/setup-terraform@v2

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Workspace Select or Create
        if: github.event_name == 'pull_request'
        id: workspace_pr
        run: |
          WORKSPACES=$(terraform workspace list)
          if ! echo $WORKSPACES | grep -q $GITHUB_HEAD_REF; then
            terraform workspace new $GITHUB_HEAD_REF
          fi
            terraform workspace select $GITHUB_HEAD_REF

      - name: Terraform Workspace Select or Create
        if: github.event_name != 'pull_request'
        id: workspace
        run: |
          WORKSPACES=$(terraform workspace list)
          if ! echo $WORKSPACES | grep -q $GITHUB_REF_NAME; then
            terraform workspace new $GITHUB_REF_NAME
          fi
            terraform workspace select $GITHUB_REF_NAME

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      # - name: Terraform Plan
      #   id: plan
      #   run: terraform plan -no-color
      #   continue-on-error: false

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve -no-color
        continue-on-error: false

      # - name: Terraform Output
      #   id: output
      #   run: |
      #     CLOUDRUN_URL=$(terraform output cloudrun_url | tr -d '"' | tr -d '\n')
      #     echo "CLOUDRUN_URL=$CLOUDRUN_URL" >> $GITHUB_OUTPUT

      - name: Post URL to PR
        uses: actions-cool/issues-helper@v2
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Infrastructure has been deployed :muscle:

            ...now let's get the app deployed!

