name: Docker Deploy

on:
  #push:
  #  branches: [ "main" ]
  workflow_dispatch:
  workflow_call:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Get branch name
      id: get_branch_name
      run: |
        if [ $GITHUB_HEAD_REF == "" ]; then
          echo "GITHUB_HEAD_REF is empty"
          BRANCH=$GITHUB_REF_NAME
        else
          echo "GITHUB_HEAD_REF is not empty"
          BRANCH=$GITHUB_HEAD_REF
        fi
        echo $GITHUB_HEAD_REF
        echo $GITHUB_REF_NAME
        echo $BRANCH
        echo "BRANCH=$BRANCH" >> $GITHUB_OUTPUT

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.GCP_SA_CREDENTIAL }}
        token_format: access_token

    #This example runs "docker login" directly to Artifact Registry.
    - uses: docker/login-action@v1
      with:
        registry: us-east1-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag us-east1-docker.pkg.dev/acampbell-sc-lab/artifacts-${{ steps.get_branch_name.outputs.BRANCH }}/timecard-memer:${{ github.sha }}
      working-directory: containers/timecard-memer

    - name: Push the Docker image
      run: |
        docker push us-east1-docker.pkg.dev/acampbell-sc-lab/artifacts-${{ steps.get_branch_name.outputs.BRANCH }}/timecard-memer:${{ github.sha }}
      working-directory: containers/timecard-memer

    - name: Deploy Docker image to Cloud Run
      run: |
        gcloud run deploy cloudrun-${{ steps.get_branch_name.outputs.BRANCH }} --image us-east1-docker.pkg.dev/acampbell-sc-lab/artifacts-${{ steps.get_branch_name.outputs.BRANCH }}/timecard-memer:${{ github.sha }} --platform managed --region us-east1 --allow-unauthenticated --port 8000
      working-directory: containers/timecard-memer

    - name: Get the Cloud Run URL
      id: get_url
      run: |
        URL=$(gcloud run services describe cloudrun-${{ steps.get_branch_name.outputs.BRANCH }} --region us-east1 --format 'value(status.url)')
        echo $URL
        echo "CLOUDRUN_URL=$URL" >> $GITHUB_OUTPUT

    - name: Print the Cloud Run URL
      run: |
        echo "Obtained Cloud Run URL: ${{ steps.get_url.outputs.CLOUDRUN_URL }}"

    - name: Post comment to PR
      if: github.event_name == 'pull_request'
      uses: actions-cool/issues-helper@v2
      with:
        actions: 'create-comment'
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          :rocket: Application has been deployed to ${{ steps.get_url.outputs.CLOUDRUN_URL }}.


